import assert from "node:assert/strict";
import { test } from "node:test";
import { decideSalesReply } from "./agentProvider.ts";
import { defaultAgentSettings, canEnableAgent } from "./agentSettings.ts";
import { PROVIDER_KEYS, SALES_AI_PROVIDERS, providerStatuses, resolveSalesProvider } from "./providerConfig.ts";
const decision={action:"reply",text:"Welcome to Sunchaser. Which city are you in?"};
const replies:any={
 gemini:{candidates:[{finishReason:"STOP",content:{parts:[{text:JSON.stringify(decision)}]}}]},
 openai:{status:"completed",output:[{type:"message",content:[{type:"output_text",text:JSON.stringify(decision)}]}]},
 grok:{status:"completed",output:[{type:"message",content:[{type:"output_text",text:JSON.stringify(decision)}]}]},
 claude:{stop_reason:"tool_use",content:[{type:"tool_use",name:"sales_agent_decision",input:decision}]}
};
const endpoints={gemini:"generativelanguage.googleapis.com",openai:"api.openai.com",grok:"api.x.ai",claude:"api.anthropic.com"};
for(const provider of SALES_AI_PROVIDERS) test(`${provider}: fixed host, correct authentication, schema and safe response`,async()=>{
 const keyName=PROVIDER_KEYS[provider],previous=process.env[keyName];process.env[keyName]="fixture-secret";
 let calls=0;
 const fetcher:typeof fetch=async(input,init)=>{calls++;assert.equal(new URL(String(input)).hostname,endpoints[provider]);assert.ok(init?.signal);const headers=new Headers(init?.headers);assert.equal(headers.get(provider==="gemini" ? "x-goog-api-key" : provider==="claude" ? "x-api-key" : "authorization"),provider==="openai" || provider==="grok" ? "Bearer fixture-secret" : "fixture-secret");assert.equal(String(input).includes("fixture-secret"),false);const body=JSON.parse(String(init?.body));assert.equal(JSON.stringify(body).includes("fixture-secret"),false);if(provider==="openai" || provider==="grok"){assert.equal(body.store,false);assert.equal(body.text.format.type,"json_schema");assert.equal(body.model,"fixture-model");}if(provider==="claude")assert.equal(body.tool_choice.name,"sales_agent_decision");return Response.json(replies[provider]);};
 try{assert.deepEqual(await decideSalesReply({...defaultAgentSettings(),provider,model:"fixture-model"},[{role:"customer",text:"hello"}],AbortSignal.timeout(1000),fetcher),decision);assert.equal(calls,1);}finally{if(previous===undefined)delete process.env[keyName];else process.env[keyName]=previous;}
});
test("provider selection never borrows another provider's credentials",()=>{const env={OPENAI_API_KEY:"openai-fixture",WHATSAPP_SALES_AI_MODEL:"fixture-model"};assert.equal(resolveSalesProvider(env,{provider:"grok"}).apiKey,"");assert.equal(resolveSalesProvider(env,{provider:"openai"}).apiKey,"openai-fixture");assert.throws(()=>resolveSalesProvider(env,{provider:"invalid" as any}));assert.throws(()=>resolveSalesProvider(env,{model:"../../leak?secret"}));assert.equal(JSON.stringify(providerStatuses(env)).includes("openai-fixture"),false);});
test("selected key and explicit model are required for readiness",()=>{const env={OPENAI_API_KEY:"fixture",WHATSAPP_CONVERSATIONS_ENABLED:"true",RAILWAY_S3_ENDPOINT:"https://storage.example.test",RAILWAY_S3_BUCKET:"test",RAILWAY_S3_ACCESS_KEY_ID:"test",RAILWAY_S3_SECRET_ACCESS_KEY:"test",RAILWAY_OBJECT_PROXY_SECRET:"fixture-proxy-secret",WHATSAPP_SALES_AGENT_AUTONOMOUS_SEND:"true"};assert.equal(canEnableAgent(env,{provider:"openai",model:"fixture-model"}),true);assert.equal(canEnableAgent(env,{provider:"grok",model:"fixture-model"}),false);assert.equal(canEnableAgent(env,{provider:"openai",model:""}),false);});
test("HTTP failure is sanitized and causes no retries or paid provider fallback",async()=>{const previous=process.env.OPENAI_API_KEY;process.env.OPENAI_API_KEY="fixture";let calls=0;try{await assert.rejects(decideSalesReply({...defaultAgentSettings(),provider:"openai",model:"fixture-model"},[],AbortSignal.timeout(1000),async()=>{calls++;return new Response("sensitive credential or prompt",{status:401});}),/HTTP 401/);assert.equal(calls,1);}finally{if(previous===undefined)delete process.env.OPENAI_API_KEY;else process.env.OPENAI_API_KEY=previous;}});
test("incomplete, refused and malformed provider responses cannot send",async()=>{const previous=process.env.OPENAI_API_KEY;process.env.OPENAI_API_KEY="fixture";try{for(const result of [{status:"incomplete",output:[]},{status:"completed",output:[{type:"message",content:[{type:"refusal",refusal:"No"}]}]},{status:"completed",output:[{type:"message",content:[{type:"output_text",text:"invalid json"}]}]}])await assert.rejects(decideSalesReply({...defaultAgentSettings(),provider:"openai",model:"fixture-model"},[],AbortSignal.timeout(1000),async()=>Response.json(result)));}finally{if(previous===undefined)delete process.env.OPENAI_API_KEY;else process.env.OPENAI_API_KEY=previous;}});
