import type { DeliveryChallan } from "./src/lib/deliveryManagement.ts";
import { qrCodeImageUrl } from "./src/lib/deliveryQr.ts";

function esc(s: unknown) {
  return String(s ?? "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

export function compileDeliveryChallanHtml(input: {
  challan: DeliveryChallan;
  invoice?: { invoiceNumber?: string; customerName?: string; customerAddress?: string } | null;
  branding?: { companyName?: string; logoUrl?: string; primaryColor?: string };
  verificationUrl: string;
}) {
  const { challan, invoice, branding, verificationUrl } = input;
  const company = branding?.companyName || "Sunchaser Energy Systems";
  const logo = branding?.logoUrl || "";
  const primary = branding?.primaryColor || "#f59e0b";
  const items = challan.items || [];
  const qrUrl = qrCodeImageUrl(verificationUrl, 180);

  const itemRows = items
    .map(
      (it) => `<tr>
      <td>${esc(it.itemName)}</td>
      <td style="text-align:center">${esc(it.deliverNowQty)}</td>
      <td style="text-align:center">${esc(it.invoiceQty)}</td>
      <td>${esc(it.serialNumber || "—")}</td>
    </tr>`
    )
    .join("");

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<title>Delivery Challan — ${esc(challan.challanNumber)}</title>
<style>
  body { font-family: Arial, sans-serif; color: #111; margin: 24px; font-size: 12px; }
  .header { display: flex; align-items: center; gap: 16px; border-bottom: 3px solid ${primary}; padding-bottom: 12px; margin-bottom: 20px; }
  .header img { max-height: 56px; }
  h1 { margin: 0; font-size: 20px; color: ${primary}; }
  .meta { display: grid; grid-template-columns: 1fr 1fr; gap: 8px 24px; margin-bottom: 20px; }
  table { width: 100%; border-collapse: collapse; margin: 16px 0; }
  th, td { border: 1px solid #ccc; padding: 8px; text-align: left; }
  th { background: #f5f5f5; font-size: 10px; text-transform: uppercase; }
  .verify-box { border: 2px dashed ${primary}; border-radius: 12px; padding: 16px; margin-top: 24px; display: flex; gap: 20px; align-items: center; flex-wrap: wrap; }
  .verify-box img { width: 140px; height: 140px; }
  .verify-url { word-break: break-all; font-family: monospace; font-size: 11px; color: #333; }
</style>
</head>
<body>
  <div class="header">
    ${logo ? `<img src="${esc(logo)}" alt="Logo"/>` : ""}
    <div>
      <h1>${esc(company)}</h1>
      <div>Delivery Challan</div>
    </div>
  </div>

  <div class="meta">
    <div><strong>Challan #:</strong> ${esc(challan.challanNumber)}</div>
    <div><strong>Invoice #:</strong> ${esc(invoice?.invoiceNumber || "—")}</div>
    <div><strong>Customer:</strong> ${esc(invoice?.customerName || "—")}</div>
    <div><strong>Site Address:</strong> ${esc(invoice?.customerAddress || "—")}</div>
    <div><strong>Delivery Date:</strong> ${esc(challan.deliveryDate || "—")}</div>
    <div><strong>Vehicle:</strong> ${esc(challan.vehicleNumber || "—")}</div>
    <div><strong>Driver:</strong> ${esc(challan.driverName || "—")}</div>
    <div><strong>Installer:</strong> ${esc(challan.installerName || "—")}</div>
  </div>

  <h2>Material List</h2>
  <table>
    <thead><tr><th>Item</th><th>Deliver Qty</th><th>Invoice Qty</th><th>Serial #</th></tr></thead>
    <tbody>${itemRows || "<tr><td colspan='4'>No items</td></tr>"}</tbody>
  </table>

  <div class="verify-box">
    <img src="${esc(qrUrl)}" alt="Verification QR Code"/>
    <div>
      <strong style="color:${primary}">Customer Verification</strong>
      <p>Scan this QR code or open the link to confirm material receipt.</p>
      <p class="verify-url">${esc(verificationUrl)}</p>
      <p style="font-size:10px;color:#666;margin-top:8px;">Valid until ${esc(challan.tokenExpiresAt?.slice(0, 10) || "—")}</p>
    </div>
  </div>

  <p style="font-size:10px;color:#666;margin-top:32px;">Generated by Sunchaser CRM · ${new Date().toISOString()}</p>
</body>
</html>`;
}
