import assert from "node:assert/strict";
import express from "express";
import { createQuotePdfUploadToken, verifyQuotePdfUploadToken, parseQuotePdfBase64, quotePdfObjectKey, addPdfArchiveToNotes } from "./smartQuotePdfArchive";
import { createPublicLeadRouter } from "./publicLeadRoutes";
import { parseSmartQuotePdfArchive, visibleLeadNotes } from "../../src/lib/smartQuoteLead";
import { isPublicApiRoute } from "../middleware/publicRoutes";
process.env.JWT_SECRET = "archive-tests-only-secret-at-least-32-characters";
const leadId = "lead-11111111-1111-4111-8111-111111111111", quoteNumber = "SES-20261004-1234";
const now = Date.now(), token = createQuotePdfUploadToken(leadId, quoteNumber, now);
assert.equal(verifyQuotePdfUploadToken(leadId, quoteNumber, token, now), true);
assert.equal(verifyQuotePdfUploadToken(leadId, "SES-20261004-4321", token, now), false);
assert.equal(verifyQuotePdfUploadToken("lead-22222222-2222-4222-8222-222222222222", quoteNumber, token, now), false);
assert.equal(verifyQuotePdfUploadToken(leadId, quoteNumber, token, now + 24 * 60 * 60 * 1000 + 1), false);
assert.equal(verifyQuotePdfUploadToken(leadId, quoteNumber, token, now - 1), false);
assert.equal(verifyQuotePdfUploadToken(leadId, quoteNumber, token + "x", now), false);
const pdf = Buffer.from("%PDF-1.4\nfixture\n%%EOF");
assert.deepEqual(parseQuotePdfBase64(pdf.toString("base64")), pdf);
assert.throws(() => parseQuotePdfBase64(Buffer.from("not-pdf").toString("base64")));
assert.throws(() => parseQuotePdfBase64("A".repeat(8 * 1024 * 1024)));
const key = quotePdfObjectKey(leadId, quoteNumber, pdf);
assert.equal(key, quotePdfObjectKey(leadId, quoteNumber, pdf));
const archive = { quoteNumber, fileName: quoteNumber + ".pdf", fileUrl: "/api/storage/object/customer-documents/file?sig=test", sha256: "hash", sizeBytes: pdf.length, savedAt: new Date(now).toISOString() };
const notes = "Staff note\nSMART_QUOTE_V1\nSnapshot: {}";
const updated = addPdfArchiveToNotes(notes, archive);
assert.deepEqual(parseSmartQuotePdfArchive(updated), archive);
assert.equal(addPdfArchiveToNotes(updated, archive), updated);
assert.equal(visibleLeadNotes(updated), "Staff note\nSMART_QUOTE_V1");
assert.equal(isPublicApiRoute("POST", "/api/public/smart-quote-pdf"), true);
assert.equal(isPublicApiRoute("GET", "/api/public/smart-quote-pdf"), false);
assert.equal(isPublicApiRoute("DELETE", "/api/public/smart-quote-pdf"), false);
const app = express(); app.use(express.json({ limit: "8mb" }));
let archiveCalls = 0, failArchive = false;
app.use("/api/public", createPublicLeadRouter({ persistLead: async () => ({ leadId }), archivePdf: async (id, number, bytes) => {
  assert.equal(id, leadId); assert.equal(number, quoteNumber); assert.deepEqual(bytes, pdf);
  archiveCalls++; if (failArchive) throw new Error("storage failed"); return archive;
}, rateLimit: (_req, _res, next) => next() }));
const server = app.listen(0, "127.0.0.1");
await new Promise<void>(resolve => server.once("listening", resolve));
const address = server.address() as { port: number };
const post = (body: unknown) => fetch(`http://127.0.0.1:${address.port}/api/public/smart-quote-pdf`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) });
try {
  assert.equal((await post({ leadId, quoteNumber, uploadToken: "invalid", pdfBase64: pdf.toString("base64") })).status, 403);
  assert.equal(archiveCalls, 0);
  assert.equal((await post({ leadId, quoteNumber, uploadToken: token, pdfBase64: "bm90LXBkZg==" })).status, 400);
  assert.equal(archiveCalls, 0);
  const res = await post({ leadId, quoteNumber, uploadToken: token, pdfBase64: pdf.toString("base64") });
  assert.equal(res.status, 201); assert.deepEqual((await res.json()).archive, archive); assert.equal(archiveCalls, 1);
  failArchive = true;
  assert.equal((await post({ leadId, quoteNumber, uploadToken: token, pdfBase64: pdf.toString("base64") })).status, 500);
} finally { await new Promise<void>((resolve, reject) => server.close(err => err ? reject(err) : resolve())); }
console.log("PDF archive authorization, expiry, cross-lead rejection, payload checks, retry and failure tests passed.");
