-- Phase 2 rollback. GENERATED by scripts/saas/generate-phase2-sql.mjs. Safe while only the founding company exists.
-- Copies membership/company data to schema app_rollback_backup first. Restores dropped policies, row-security flags,
-- column defaults and function privileges recorded by the up migration.
begin;
set local lock_timeout = '15s';
create schema if not exists app_rollback_backup;
create table if not exists app_rollback_backup.companies as select * from public.companies;
create table if not exists app_rollback_backup.company_memberships as select * from public.company_memberships;

do $$
declare
  tenant_new text[] := array['activity_logs','after_sales_service_logs','bank_accounts','bills','categories','ceo_messages','company_terms','customer_documents','customer_energy_devices','customer_equipment','customer_portal_profiles','customer_savings_profiles','customer_subscriptions','customer_systems','customer_warranties','customers','delivery_challan_items','delivery_challan_photos','delivery_challans','design_sessions','energy_alerts','installation_photos','installation_tasks','interactive_proposal_events','interactive_proposals','internal_costing_sheets','inventory_items','inventory_movements','inventory_purchases','investors','invoice_items','invoice_payments','invoices','leads','net_metering_trackers','notifications','orders','party_ledger_archives','payments','products','products_inventory','project_completion_media','project_deliveries','project_delivery_items','project_delivery_updates','project_finance_records','project_installation_photos','project_installed_equipment','project_inventory_reservations','projects','purchase_orders','quotations','quote_pdf_settings','quote_template_pages','quote_templates','service_requests','service_visit_photos','service_visit_reports','settings','site_surveys','smart_quote_versions','social_links','solar_packages','structure_descriptions','subscription_payments','subscription_plans','support_ticket_updates','support_tickets','technical_job_updates','warranties','warranty_claims','website_content','whatsapp_logs','whatsapp_message_logs']::text[];
  tenant_existing text[] := array['whatsapp_audit_events','whatsapp_channels','whatsapp_connections','whatsapp_contacts','whatsapp_conversation_assignment_events','whatsapp_conversation_crm_links','whatsapp_conversation_status_events','whatsapp_conversations','whatsapp_message_status_events','whatsapp_messages','whatsapp_oauth_states','whatsapp_outbound_idempotency_keys','whatsapp_read_watermarks','whatsapp_webhook_events']::text[];
  role_template text[] := array['role_permissions','roles']::text[];
  t text; p record; f record; orig text;
begin
  if (select count(*) from public.companies where id <> 'sunchaser') > 0 then
    raise exception 'Rollback refused: companies other than sunchaser exist. Export or remove their data first.';
  end if;
  foreach t in array tenant_new || tenant_existing || role_template loop
    if to_regclass('public.' || t) is null then continue; end if;
    execute format('drop policy if exists tenant_isolation on public.%I', t);
    execute format('drop policy if exists tenant_select on public.%I', t);
    execute format('drop policy if exists tenant_insert on public.%I', t);
    execute format('drop policy if exists tenant_update on public.%I', t);
    execute format('drop policy if exists tenant_delete on public.%I', t);
    execute format('revoke all on public.%I from crm_tenant', t);
    if exists (select 1 from app.original_state where kind = 'created_fk' and name = t) then
      execute format('alter table public.%I drop constraint if exists %I', t, t || '_company_fk');
    end if;
    if exists (select 1 from app.original_state where kind = 'created_index' and name = t) then
      execute format('drop index if exists public.%I', t || '_company_idx');
    end if;
    if exists (select 1 from app.original_state where kind = 'created_column' and name = t) then
      execute format('alter table public.%I drop column if exists company_id', t);
    else
      select value into orig from app.original_state where kind = 'column_default' and name = t;
      if coalesce(orig, '') = '' then
        execute format('alter table public.%I alter column company_id drop default', t);
      else
        execute format('alter table public.%I alter column company_id set default %s', t, orig);
      end if;
    end if;
    select value into orig from app.original_state where kind = 'relrowsecurity' and name = t;
    if orig = 'false' then execute format('alter table public.%I disable row level security', t); end if;
  end loop;

  for p in select * from app.dropped_policies order by id loop
    if to_regclass(format('%I.%I', p.schema_name, p.table_name)) is null then continue; end if;
    if exists (select 1 from pg_policies where schemaname = p.schema_name and tablename = p.table_name and policyname = p.policy_name) then continue; end if;
    execute format('create policy %I on %I.%I as %s for %s to %s%s%s',
      p.policy_name, p.schema_name, p.table_name, p.permissive, p.cmd,
      (select string_agg(case when r = 'public' then 'public' else quote_ident(r) end, ', ') from unnest(p.roles) r),
      case when p.qual is not null then ' using (' || p.qual || ')' else '' end,
      case when p.with_check is not null then ' with check (' || p.with_check || ')' else '' end);
  end loop;

  for f in select name from app.original_state where kind = 'function_public_execute' loop
    begin
      execute format('grant execute on function %s to public', f.name);
    exception when undefined_function then null; end;
  end loop;
end $$;

drop table if exists public.company_memberships;
alter table public.users drop column if exists is_platform_admin;
drop policy if exists tenant_sees_own_company on public.companies;
drop table if exists public.companies cascade;
revoke all on all sequences in schema public from crm_tenant;
revoke usage on schema public from crm_tenant;
drop schema if exists app cascade;
do $$ begin
  if exists (select 1 from pg_roles where rolname = 'crm_tenant') then drop role crm_tenant; end if;
end $$;
notify pgrst, 'reload schema';
commit;
