-- Phase 2: company foundation (additive, idempotent). GENERATED by scripts/saas/generate-phase2-sql.mjs
-- from scripts/saas/table-classification.json. Do not edit by hand; edit the classification and regenerate.
-- Not run in production. Apply only after the read-only preflight passes and a restored backup exists (gate G3).
-- Single transaction: any failure rolls everything back. Existing rows are not rewritten (constant column default).
begin;
set local lock_timeout = '15s';
set local statement_timeout = '20min';

create schema if not exists app;
create table if not exists app.config (key text primary key, value text not null);
insert into app.config (key, value) values ('strict_company', 'off') on conflict (key) do nothing;
create table if not exists app.dropped_policies (
  id bigserial primary key, schema_name text not null, table_name text not null, policy_name text not null,
  permissive text not null, roles text[] not null, cmd text not null, qual text, with_check text,
  dropped_at timestamptz not null default now());
create table if not exists app.original_state (
  kind text not null, name text not null, value text not null, recorded_at timestamptz not null default now(),
  primary key (kind, name));

-- The company a request acts for: the x-company-id header sent by the CRM server on the tenant connection.
create or replace function app.request_company_id() returns text
language plpgsql stable as $f$
declare h text;
begin
  h := nullif(current_setting('request.headers', true), '');
  if h is null then return null; end if;
  return nullif(h::json ->> 'x-company-id', '');
end $f$;

-- Column default. Tenant requests always use the header. Platform/system writes fall back to the founding
-- company only while app.config strict_company = 'off' (single-company compatibility); at go-live set it to 'on'.
create or replace function app.default_company_id() returns text
language plpgsql stable as $f$
declare c text;
begin
  c := app.request_company_id();
  if c is not null then return c; end if;
  if (select value from app.config where key = 'strict_company') = 'on' then return null; end if;
  return 'sunchaser';
end $f$;

create table if not exists public.companies (
  id text primary key check (id ~ '^[a-z][a-z0-9_]{1,40}$'),
  slug text not null unique check (slug ~ '^[a-z0-9][a-z0-9-]{1,40}$'),
  name text not null,
  status text not null default 'active' check (status in ('trial','active','suspended','cancelled')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now());
insert into public.companies (id, slug, name, status) values ('sunchaser', 'sunchaser', 'Sunchaser Energy Systems', 'active')
  on conflict (id) do nothing;

alter table public.users add column if not exists is_platform_admin boolean not null default false;

create table if not exists public.company_memberships (
  id text primary key,
  company_id text not null references public.companies(id),
  user_id text not null references public.users(id) on delete cascade,
  role text not null,
  status text not null default 'active' check (status in ('invited','active','suspended','removed')),
  invited_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (company_id, user_id));
create index if not exists company_memberships_user_idx on public.company_memberships (user_id);

-- Staff of the existing business become members of the founding company with their current role.
-- Portal customers (role Customer) are not members: their company comes from their customer record.
insert into public.company_memberships (id, company_id, user_id, role, status)
select 'mem-sunchaser-' || u.id, 'sunchaser', u.id, u.role,
       case u.account_status when 'Approved' then 'active' when 'Suspended' then 'suspended' when 'Pending' then 'invited' else 'removed' end
from public.users u
where u.role <> 'Customer'
on conflict (company_id, user_id) do nothing;

do $$ begin
  if not exists (select 1 from pg_roles where rolname = 'crm_tenant') then create role crm_tenant nologin noinherit; end if;
  if exists (select 1 from pg_roles where rolname = 'authenticator') then grant crm_tenant to authenticator; end if;
end $$;
grant usage on schema public to crm_tenant;
grant usage on schema app to crm_tenant, service_role;  -- service_role evaluates the column defaults too
grant execute on function app.request_company_id(), app.default_company_id() to crm_tenant, service_role;
grant select on app.config to crm_tenant, service_role;
grant select on public.companies to crm_tenant;
grant select, insert, update, delete on public.companies, public.company_memberships to service_role;
alter table public.companies enable row level security;
alter table public.company_memberships enable row level security;
drop policy if exists tenant_sees_own_company on public.companies;
create policy tenant_sees_own_company on public.companies for select to crm_tenant using (id = (select app.request_company_id()));

do $$
declare
  tenant_new text[] := array['activity_logs','after_sales_service_logs','bank_accounts','bills','categories','ceo_messages','company_terms','customer_documents','customer_energy_devices','customer_equipment','customer_portal_profiles','customer_savings_profiles','customer_subscriptions','customer_systems','customer_warranties','customers','delivery_challan_items','delivery_challan_photos','delivery_challans','design_sessions','energy_alerts','installation_photos','installation_tasks','interactive_proposal_events','interactive_proposals','internal_costing_sheets','inventory_items','inventory_movements','inventory_purchases','investors','invoice_items','invoice_payments','invoices','leads','net_metering_trackers','notifications','orders','party_ledger_archives','payments','products','products_inventory','project_completion_media','project_deliveries','project_delivery_items','project_delivery_updates','project_finance_records','project_installation_photos','project_installed_equipment','project_inventory_reservations','projects','purchase_orders','quotations','quote_pdf_settings','quote_template_pages','quote_templates','service_requests','service_visit_photos','service_visit_reports','settings','site_surveys','smart_quote_versions','social_links','solar_packages','structure_descriptions','subscription_payments','subscription_plans','support_ticket_updates','support_tickets','technical_job_updates','warranties','warranty_claims','website_content','whatsapp_logs','whatsapp_message_logs']::text[];
  tenant_existing text[] := array['whatsapp_audit_events','whatsapp_channels','whatsapp_connections','whatsapp_contacts','whatsapp_conversation_assignment_events','whatsapp_conversation_crm_links','whatsapp_conversation_status_events','whatsapp_conversations','whatsapp_message_status_events','whatsapp_messages','whatsapp_oauth_states','whatsapp_outbound_idempotency_keys','whatsapp_read_watermarks','whatsapp_webhook_events']::text[];
  role_template text[] := array['role_permissions','roles']::text[];
  no_access text[] := array['learning_assessments','learning_courses','learning_enrollments','learning_generation_jobs','learning_usage_events','messaging_attachments','messaging_audit_logs','messaging_contact_identities','messaging_contacts','messaging_conversation_assignments','messaging_conversations','messaging_messages','messaging_outbox','messaging_status_events','mp_audit_events','mp_auto_import_listings','mp_auto_import_sync_runs','mp_brands','mp_cart_items','mp_carts','mp_categories','mp_delivery_rates','mp_delivery_zones','mp_event_outbox','mp_field_overrides','mp_idempotency_keys','mp_import_reject_ledger','mp_job_runs','mp_media','mp_order_items','mp_orders','mp_payment_plans','mp_payments','mp_price_alerts','mp_price_history','mp_price_overrides','mp_pricing_config','mp_product_costs','mp_product_variants','mp_products','mp_receipt_objects','mp_receipts','mp_storage_cleanup_outbox','mp_supplier_observations','mp_supplier_products','mp_suppliers','mp_upload_intents','users','whatsapp_web_owner_diagnostics','whatsapp_web_session_lease','whatsapp_web_sync_jobs']::text[];
  t text; p record; skipped text[] := '{}';
begin
  -- Record the original row-security flag of every table we touch so rollback can restore it.
  foreach t in array tenant_new || tenant_existing || role_template loop
    if to_regclass('public.' || t) is null then skipped := skipped || t; continue; end if;
    insert into app.original_state (kind, name, value)
      select 'relrowsecurity', t, c.relrowsecurity::text from pg_class c where c.oid = ('public.' || t)::regclass
      on conflict do nothing;

    -- Remember what existed before, so rollback only undoes what this migration did.
    if not exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = t and column_name = 'company_id') then
      insert into app.original_state (kind, name, value) values ('created_column', t, 'company_id') on conflict do nothing;
    else
      insert into app.original_state (kind, name, value)
        select 'column_default', t, coalesce(pg_get_expr(d.adbin, d.adrelid), '')
        from pg_attribute a left join pg_attrdef d on d.adrelid = a.attrelid and d.adnum = a.attnum
        where a.attrelid = ('public.' || t)::regclass and a.attname = 'company_id'
        on conflict do nothing;
    end if;

    if t = any(tenant_new) then
      -- constant default => metadata-only, existing rows keep their timestamps and triggers do not fire
      execute format('alter table public.%I add column if not exists company_id text not null default %L', t, 'sunchaser');
      execute format('alter table public.%I alter column company_id set default app.default_company_id()', t);
    elsif t = any(tenant_existing) then
      execute format('alter table public.%I alter column company_id set default app.default_company_id()', t);
    else
      execute format('alter table public.%I add column if not exists company_id text', t);
      execute format('alter table public.%I alter column company_id set default app.default_company_id()', t);
    end if;

    if not exists (select 1 from pg_constraint where conrelid = ('public.' || t)::regclass and conname = t || '_company_fk') then
      execute format('alter table public.%I add constraint %I foreign key (company_id) references public.companies(id)', t, t || '_company_fk');
      insert into app.original_state (kind, name, value) values ('created_fk', t, t || '_company_fk') on conflict do nothing;
    end if;
    if to_regclass('public.' || t || '_company_idx') is null then
      execute format('create index %I on public.%I (company_id)', t || '_company_idx', t);
      insert into app.original_state (kind, name, value) values ('created_index', t, t || '_company_idx') on conflict do nothing;
    end if;

    -- Legacy policies open to PUBLIC/anon/authenticated (using (true)) would be OR-ed with ours and defeat isolation.
    for p in select * from pg_policies where schemaname = 'public' and tablename = t and policyname not like 'tenant_%'
             and (roles && array['public','anon','authenticated','crm_tenant']::name[]) loop
      insert into app.dropped_policies (schema_name, table_name, policy_name, permissive, roles, cmd, qual, with_check)
        values (p.schemaname, p.tablename, p.policyname, p.permissive, p.roles::text[], p.cmd, p.qual, p.with_check);
      execute format('drop policy %I on public.%I', p.policyname, t);
    end loop;

    execute format('alter table public.%I enable row level security', t);
    if t = any(role_template) then
      -- company_id NULL = system template: readable by every company, writable by none.
      execute format('drop policy if exists tenant_select on public.%I', t);
      execute format('create policy tenant_select on public.%I for select to crm_tenant using (company_id is null or company_id = (select app.request_company_id()))', t);
      execute format('drop policy if exists tenant_insert on public.%I', t);
      execute format('drop policy if exists tenant_update on public.%I', t);
      execute format('drop policy if exists tenant_delete on public.%I', t);
      execute format('create policy tenant_insert on public.%I for insert to crm_tenant with check (company_id = (select app.request_company_id()))', t);
      execute format('create policy tenant_update on public.%I for update to crm_tenant using (company_id = (select app.request_company_id())) with check (company_id = (select app.request_company_id()))', t);
      execute format('create policy tenant_delete on public.%I for delete to crm_tenant using (company_id = (select app.request_company_id()))', t);
    else
      execute format('drop policy if exists tenant_isolation on public.%I', t);
      execute format('create policy tenant_isolation on public.%I for all to crm_tenant using (company_id = (select app.request_company_id())) with check (company_id = (select app.request_company_id()))', t);
    end if;
    execute format('grant select, insert, update, delete on public.%I to crm_tenant', t);
  end loop;

  -- Tables the tenant role must never reach: make sure it holds no privilege on them.
  foreach t in array no_access loop
    if to_regclass('public.' || t) is null then continue; end if;
    execute format('revoke all on public.%I from crm_tenant', t);
  end loop;

  insert into app.original_state (kind, name, value) values ('skipped_missing_tables', 'phase2', array_to_string(skipped, ','))
    on conflict (kind, name) do update set value = excluded.value;
  if array_length(skipped, 1) > 0 then raise notice 'Tables in the classification but absent in this database: %', skipped; end if;
end $$;

grant usage, select on all sequences in schema public to crm_tenant;

-- SECURITY DEFINER / owner-run functions bypass row security. The tenant role must not execute any application
-- function until that function has been reviewed and re-granted explicitly. EXECUTE is granted to PUBLIC by
-- default, so keep service_role working first, then revoke PUBLIC. Extension-owned functions are left alone.
do $$
declare f record;
begin
  for f in select p.oid, p.oid::regprocedure::text as sig from pg_proc p join pg_namespace n on n.oid = p.pronamespace
           where n.nspname = 'public' and p.prokind in ('f','p')
             and not exists (select 1 from pg_depend d where d.objid = p.oid and d.deptype = 'e') loop
    if has_function_privilege('public', f.oid, 'execute') or has_function_privilege('crm_tenant', f.oid, 'execute') then
      insert into app.original_state (kind, name, value) values ('function_public_execute', f.sig, 'granted') on conflict do nothing;
      execute format('grant execute on function %s to service_role', f.sig);
      execute format('revoke execute on function %s from public', f.sig);
      execute format('revoke execute on function %s from crm_tenant', f.sig);
    end if;
  end loop;
end $$;

-- Same-company references. Row security only looks at a row's own company_id; a foreign key only proves the parent
-- exists. Without this, company A could insert a child row pointing at company B's parent, and any server-side
-- aggregate computed by parent id would include it. SECURITY DEFINER so the parent is found despite row security;
-- it only compares company ids and is a trigger function (not callable through the API).
create or replace function app.assert_same_company() returns trigger
language plpgsql security definer set search_path = public, pg_temp as $f$
declare i int := 0; col text; ptab text; pcol text; ptype text; v text; pc text; hit boolean; nv jsonb := to_jsonb(NEW);
begin
  while i < TG_NARGS loop
    col := TG_ARGV[i]; ptab := TG_ARGV[i + 1]; pcol := TG_ARGV[i + 2]; ptype := TG_ARGV[i + 3]; i := i + 4;
    v := nv ->> col;
    if v is null then continue; end if;
    -- EXECUTE ... INTO does not set FOUND, so the query returns its own "row exists" flag.
    hit := null; pc := null;
    execute format('select company_id, true from public.%I where %I = $1::%s', ptab, pcol, ptype) into pc, hit using v;
    if hit and pc is not null and pc is distinct from NEW.company_id then
      raise exception 'cross-company reference: %.% -> %.%', TG_TABLE_NAME, col, ptab, pcol using errcode = '42501';
    end if;
  end loop;
  return NEW;
end $f$;
revoke all on function app.assert_same_company() from public;

do $$
declare
  tenant_all text[] := array['activity_logs','after_sales_service_logs','bank_accounts','bills','categories','ceo_messages','company_terms','customer_documents','customer_energy_devices','customer_equipment','customer_portal_profiles','customer_savings_profiles','customer_subscriptions','customer_systems','customer_warranties','customers','delivery_challan_items','delivery_challan_photos','delivery_challans','design_sessions','energy_alerts','installation_photos','installation_tasks','interactive_proposal_events','interactive_proposals','internal_costing_sheets','inventory_items','inventory_movements','inventory_purchases','investors','invoice_items','invoice_payments','invoices','leads','net_metering_trackers','notifications','orders','party_ledger_archives','payments','products','products_inventory','project_completion_media','project_deliveries','project_delivery_items','project_delivery_updates','project_finance_records','project_installation_photos','project_installed_equipment','project_inventory_reservations','projects','purchase_orders','quotations','quote_pdf_settings','quote_template_pages','quote_templates','service_requests','service_visit_photos','service_visit_reports','settings','site_surveys','smart_quote_versions','social_links','solar_packages','structure_descriptions','subscription_payments','subscription_plans','support_ticket_updates','support_tickets','technical_job_updates','warranties','warranty_claims','website_content','whatsapp_logs','whatsapp_message_logs','whatsapp_audit_events','whatsapp_channels','whatsapp_connections','whatsapp_contacts','whatsapp_conversation_assignment_events','whatsapp_conversation_crm_links','whatsapp_conversation_status_events','whatsapp_conversations','whatsapp_message_status_events','whatsapp_messages','whatsapp_oauth_states','whatsapp_outbound_idempotency_keys','whatsapp_read_watermarks','whatsapp_webhook_events','role_permissions','roles']::text[];
  t text; args text;
begin
  foreach t in array tenant_all loop
    if to_regclass('public.' || t) is null then continue; end if;
    select string_agg(format('%L, %L, %L, %L', a.attname, cf.relname, af.attname, format_type(af.atttypid, af.atttypmod)), ', ')
      into args
    from pg_constraint c
      join pg_attribute a on a.attrelid = c.conrelid and a.attnum = c.conkey[1]
      join pg_class cf on cf.oid = c.confrelid
      join pg_attribute af on af.attrelid = c.confrelid and af.attnum = c.confkey[1]
    where c.contype = 'f' and c.conrelid = ('public.' || t)::regclass and array_length(c.conkey, 1) = 1
      and cf.relname = any(tenant_all) and cf.relname <> t;
    if args is not null then
      execute format('drop trigger if exists tenant_ref_check on public.%I', t);
      execute format('create trigger tenant_ref_check before insert or update on public.%I for each row execute function app.assert_same_company(%s)', t, args);
      insert into app.original_state (kind, name, value) values ('created_trigger', t, 'tenant_ref_check') on conflict do nothing;
    end if;
  end loop;
end $$;

-- Post-conditions: abort the whole migration if any tenant table is not fully protected.
do $$
declare t text; bad text[] := '{}';
  tenant_all text[] := array['activity_logs','after_sales_service_logs','bank_accounts','bills','categories','ceo_messages','company_terms','customer_documents','customer_energy_devices','customer_equipment','customer_portal_profiles','customer_savings_profiles','customer_subscriptions','customer_systems','customer_warranties','customers','delivery_challan_items','delivery_challan_photos','delivery_challans','design_sessions','energy_alerts','installation_photos','installation_tasks','interactive_proposal_events','interactive_proposals','internal_costing_sheets','inventory_items','inventory_movements','inventory_purchases','investors','invoice_items','invoice_payments','invoices','leads','net_metering_trackers','notifications','orders','party_ledger_archives','payments','products','products_inventory','project_completion_media','project_deliveries','project_delivery_items','project_delivery_updates','project_finance_records','project_installation_photos','project_installed_equipment','project_inventory_reservations','projects','purchase_orders','quotations','quote_pdf_settings','quote_template_pages','quote_templates','service_requests','service_visit_photos','service_visit_reports','settings','site_surveys','smart_quote_versions','social_links','solar_packages','structure_descriptions','subscription_payments','subscription_plans','support_ticket_updates','support_tickets','technical_job_updates','warranties','warranty_claims','website_content','whatsapp_logs','whatsapp_message_logs','whatsapp_audit_events','whatsapp_channels','whatsapp_connections','whatsapp_contacts','whatsapp_conversation_assignment_events','whatsapp_conversation_crm_links','whatsapp_conversation_status_events','whatsapp_conversations','whatsapp_message_status_events','whatsapp_messages','whatsapp_oauth_states','whatsapp_outbound_idempotency_keys','whatsapp_read_watermarks','whatsapp_webhook_events']::text[];
begin
  foreach t in array tenant_all loop
    if to_regclass('public.' || t) is null then continue; end if;
    if not (select c.relrowsecurity from pg_class c where c.oid = ('public.' || t)::regclass) then bad := bad || (t || ':rls-off'); end if;
    if exists (select 1 from pg_policies where schemaname = 'public' and tablename = t and policyname not like 'tenant_%' and roles && array['public','anon','authenticated','crm_tenant']::name[]) then bad := bad || (t || ':open-policy'); end if;
    if not exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = t and column_name = 'company_id' and is_nullable = 'NO') then bad := bad || (t || ':company_id-nullable'); end if;
  end loop;
  if array_length(bad, 1) > 0 then raise exception 'Phase 2 post-condition failed: %', bad; end if;
end $$;

notify pgrst, 'reload schema';
commit;
