-- Interactive client proposal links (additive migration)
-- Public clients never access these tables directly. All reads and mutations
-- go through the CRM server using a SHA-256 hash of a high-entropy link token.
-- Do not add a quotations FK: quote ids live on leads.quotes and may not have
-- a matching public.quotations row at share time.

create table if not exists public.interactive_proposals (
  id uuid primary key default gen_random_uuid(),
  token_hash text not null unique check (length(token_hash) = 64),
  lead_id text not null,
  quotation_id text not null,
  status text not null default 'Sent'
    check (status in ('Sent', 'Viewed', 'Modified', 'Accepted', 'Revoked', 'Expired')),
  definition jsonb not null,
  current_config jsonb not null,
  accepted_calculation jsonb,
  accepted_by_name text,
  created_by text not null default '',
  viewed_at timestamptz,
  modified_at timestamptz,
  accepted_at timestamptz,
  expires_at timestamptz not null,
  created_at timestamptz not null default timezone('utc'::text, now()),
  updated_at timestamptz not null default timezone('utc'::text, now())
);

create index if not exists interactive_proposals_lead_id_idx
  on public.interactive_proposals(lead_id);
create index if not exists interactive_proposals_quotation_id_idx
  on public.interactive_proposals(quotation_id);
create index if not exists interactive_proposals_status_idx
  on public.interactive_proposals(status);

create table if not exists public.interactive_proposal_events (
  id bigint generated by default as identity primary key,
  proposal_id uuid not null references public.interactive_proposals(id) on delete cascade,
  event_type text not null check (event_type in ('created', 'viewed', 'modified', 'accepted', 'revoked')),
  configuration jsonb,
  calculation jsonb,
  created_at timestamptz not null default timezone('utc'::text, now())
);

create index if not exists interactive_proposal_events_proposal_id_idx
  on public.interactive_proposal_events(proposal_id, created_at desc);

alter table public.interactive_proposals enable row level security;
alter table public.interactive_proposal_events enable row level security;

comment on table public.interactive_proposals is
  'Immutable source quotation snapshot plus client-editable, server-priced proposal configuration.';
comment on column public.interactive_proposals.token_hash is
  'SHA-256 digest only. The raw public bearer token is never stored.';
